POST http://localhost:3500/v1.0/state/statestore
Content-Type: application/json

[{"key": "x", "value": "this is a test 2"}]

###

GET http://localhost:3500/v1.0/state/statestore/x

### 
POST http://localhost:5230/test 
Content-Type: application/json

{"Text": "catty"}

###
GET http://localhost:5230/test/ninja 
Content-Type: application/json



###
GET http://localhost:3501/v1.0/invoke/myapp/method/test/space 
Content-Type: application/json


### 
GET http://localhost:5061/hello
Content-Type: application/json



### 
POST http://localhost:5061/message
Content-Type: application/json

This is the crazy body! more text
can be sent?

